/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a9cbc634-d06c-4d7f-afc0-5804c17828fe",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_eTxykX4s0",
    "aws_user_pools_web_client_id": "7cu690ts0747fjuu49vkucvo6k",
    "oauth": {},
    "aws_user_files_s3_bucket": "tagtagstorage10413-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
